Add coverage tests for parameterized statements
SQream/pysqream pull request #39
Opened 2024-10-16 10:38 UTC by ruthap

2024-11-06 17:01 UTC, arielwsq requested changes

2024-11-06 17:01 UTC, arielwsq commented on tests/test_cursor/test_parametrized_statements.py
> +        assert sqream_cursor.fetchall() ==  ([(10.0,)] if new else [])
אני לא יודע מה אנ חושב על זה שזה 2 קייסים אחד שולח ערך ושני ריק זה בערך כמו לשלוח null אולי שווה לשאול את גיא לגבי זה, אולי שווה לפצל את הטסטים לשניים למרות שזה אוצה הלוגיקה

2024-11-06 17:12 UTC, ruthap commented on tests/test_cursor/test_parametrized_statements.py
> +        assert sqream_cursor.fetchall() == ([(new,)] * self.TEMP_TABLE_START_ROWS_AMOUNT if new else [])
It will be [(None,), (None,), (None,), (None,), (None,), (None,), (None,), (None,), (None,)]

2024-11-06 17:12 UTC, ruthap commented on tests/test_cursor/test_parametrized_statements.py
>          sqream_cursor.execute(f"select i, b from {self.TEMP_TABLE_NAME} where i in (?)", params=[(1,)])
why import? it is part of the class.

2024-11-06 17:12 UTC, ruthap commented on tests/test_cursor/test_parametrized_statements.py
> +        assert sqream_cursor.fetchall() ==  ([(10.0,)] if new else [])
זה לא ערך ריק, זה ערך NULL, הטסט בודק את הparameterized query שעובד גם עם value וגם עם NULL

2024-11-06 17:14 UTC, arielwsq requested changes

2024-11-07 08:57 UTC, arielwsq approved these changes

2024-11-07 11:55 UTC, merged